# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/linshu/Documents/4_2CIS422/sdlengine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/linshu/Documents/4_2CIS422/sdlengine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/linshu/Documents/4_2CIS422/sdlengine/CMakeFiles /home/linshu/Documents/4_2CIS422/sdlengine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/linshu/Documents/4_2CIS422/sdlengine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named engine

# Build rule for target.
engine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 engine
.PHONY : engine

# fast build rule for target.
engine/fast:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/build
.PHONY : engine/fast

core/GameManger.o: core/GameManger.cpp.o

.PHONY : core/GameManger.o

# target to build an object file
core/GameManger.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/core/GameManger.cpp.o
.PHONY : core/GameManger.cpp.o

core/GameManger.i: core/GameManger.cpp.i

.PHONY : core/GameManger.i

# target to preprocess a source file
core/GameManger.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/core/GameManger.cpp.i
.PHONY : core/GameManger.cpp.i

core/GameManger.s: core/GameManger.cpp.s

.PHONY : core/GameManger.s

# target to generate assembly for a file
core/GameManger.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/core/GameManger.cpp.s
.PHONY : core/GameManger.cpp.s

events/InputEvent.o: events/InputEvent.cpp.o

.PHONY : events/InputEvent.o

# target to build an object file
events/InputEvent.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/events/InputEvent.cpp.o
.PHONY : events/InputEvent.cpp.o

events/InputEvent.i: events/InputEvent.cpp.i

.PHONY : events/InputEvent.i

# target to preprocess a source file
events/InputEvent.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/events/InputEvent.cpp.i
.PHONY : events/InputEvent.cpp.i

events/InputEvent.s: events/InputEvent.cpp.s

.PHONY : events/InputEvent.s

# target to generate assembly for a file
events/InputEvent.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/events/InputEvent.cpp.s
.PHONY : events/InputEvent.cpp.s

events/InputHandler.o: events/InputHandler.cpp.o

.PHONY : events/InputHandler.o

# target to build an object file
events/InputHandler.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/events/InputHandler.cpp.o
.PHONY : events/InputHandler.cpp.o

events/InputHandler.i: events/InputHandler.cpp.i

.PHONY : events/InputHandler.i

# target to preprocess a source file
events/InputHandler.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/events/InputHandler.cpp.i
.PHONY : events/InputHandler.cpp.i

events/InputHandler.s: events/InputHandler.cpp.s

.PHONY : events/InputHandler.s

# target to generate assembly for a file
events/InputHandler.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/events/InputHandler.cpp.s
.PHONY : events/InputHandler.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/main.cpp.s
.PHONY : main.cpp.s

rendering/RenderCore.o: rendering/RenderCore.cpp.o

.PHONY : rendering/RenderCore.o

# target to build an object file
rendering/RenderCore.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/rendering/RenderCore.cpp.o
.PHONY : rendering/RenderCore.cpp.o

rendering/RenderCore.i: rendering/RenderCore.cpp.i

.PHONY : rendering/RenderCore.i

# target to preprocess a source file
rendering/RenderCore.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/rendering/RenderCore.cpp.i
.PHONY : rendering/RenderCore.cpp.i

rendering/RenderCore.s: rendering/RenderCore.cpp.s

.PHONY : rendering/RenderCore.s

# target to generate assembly for a file
rendering/RenderCore.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/rendering/RenderCore.cpp.s
.PHONY : rendering/RenderCore.cpp.s

rendering/Window.o: rendering/Window.cpp.o

.PHONY : rendering/Window.o

# target to build an object file
rendering/Window.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/rendering/Window.cpp.o
.PHONY : rendering/Window.cpp.o

rendering/Window.i: rendering/Window.cpp.i

.PHONY : rendering/Window.i

# target to preprocess a source file
rendering/Window.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/rendering/Window.cpp.i
.PHONY : rendering/Window.cpp.i

rendering/Window.s: rendering/Window.cpp.s

.PHONY : rendering/Window.s

# target to generate assembly for a file
rendering/Window.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/rendering/Window.cpp.s
.PHONY : rendering/Window.cpp.s

utils/Settings.o: utils/Settings.cpp.o

.PHONY : utils/Settings.o

# target to build an object file
utils/Settings.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/utils/Settings.cpp.o
.PHONY : utils/Settings.cpp.o

utils/Settings.i: utils/Settings.cpp.i

.PHONY : utils/Settings.i

# target to preprocess a source file
utils/Settings.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/utils/Settings.cpp.i
.PHONY : utils/Settings.cpp.i

utils/Settings.s: utils/Settings.cpp.s

.PHONY : utils/Settings.s

# target to generate assembly for a file
utils/Settings.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/utils/Settings.cpp.s
.PHONY : utils/Settings.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... engine"
	@echo "... edit_cache"
	@echo "... core/GameManger.o"
	@echo "... core/GameManger.i"
	@echo "... core/GameManger.s"
	@echo "... events/InputEvent.o"
	@echo "... events/InputEvent.i"
	@echo "... events/InputEvent.s"
	@echo "... events/InputHandler.o"
	@echo "... events/InputHandler.i"
	@echo "... events/InputHandler.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... rendering/RenderCore.o"
	@echo "... rendering/RenderCore.i"
	@echo "... rendering/RenderCore.s"
	@echo "... rendering/Window.o"
	@echo "... rendering/Window.i"
	@echo "... rendering/Window.s"
	@echo "... utils/Settings.o"
	@echo "... utils/Settings.i"
	@echo "... utils/Settings.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

