# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/linshu/Documents/4_2CIS422/sdlengine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/linshu/Documents/4_2CIS422/sdlengine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/linshu/Documents/4_2CIS422/sdlengine/CMakeFiles /home/linshu/Documents/4_2CIS422/sdlengine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/linshu/Documents/4_2CIS422/sdlengine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named engine

# Build rule for target.
engine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 engine
.PHONY : engine

# fast build rule for target.
engine/fast:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/build
.PHONY : engine/fast

Camera.o: Camera.cpp.o

.PHONY : Camera.o

# target to build an object file
Camera.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Camera.cpp.o
.PHONY : Camera.cpp.o

Camera.i: Camera.cpp.i

.PHONY : Camera.i

# target to preprocess a source file
Camera.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Camera.cpp.i
.PHONY : Camera.cpp.i

Camera.s: Camera.cpp.s

.PHONY : Camera.s

# target to generate assembly for a file
Camera.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Camera.cpp.s
.PHONY : Camera.cpp.s

GameLoop.o: GameLoop.cpp.o

.PHONY : GameLoop.o

# target to build an object file
GameLoop.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/GameLoop.cpp.o
.PHONY : GameLoop.cpp.o

GameLoop.i: GameLoop.cpp.i

.PHONY : GameLoop.i

# target to preprocess a source file
GameLoop.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/GameLoop.cpp.i
.PHONY : GameLoop.cpp.i

GameLoop.s: GameLoop.cpp.s

.PHONY : GameLoop.s

# target to generate assembly for a file
GameLoop.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/GameLoop.cpp.s
.PHONY : GameLoop.cpp.s

Transform.o: Transform.cpp.o

.PHONY : Transform.o

# target to build an object file
Transform.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Transform.cpp.o
.PHONY : Transform.cpp.o

Transform.i: Transform.cpp.i

.PHONY : Transform.i

# target to preprocess a source file
Transform.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Transform.cpp.i
.PHONY : Transform.cpp.i

Transform.s: Transform.cpp.s

.PHONY : Transform.s

# target to generate assembly for a file
Transform.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/Transform.cpp.s
.PHONY : Transform.cpp.s

core/GameManager.o: core/GameManager.cpp.o

.PHONY : core/GameManager.o

# target to build an object file
core/GameManager.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/core/GameManager.cpp.o
.PHONY : core/GameManager.cpp.o

core/GameManager.i: core/GameManager.cpp.i

.PHONY : core/GameManager.i

# target to preprocess a source file
core/GameManager.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/core/GameManager.cpp.i
.PHONY : core/GameManager.cpp.i

core/GameManager.s: core/GameManager.cpp.s

.PHONY : core/GameManager.s

# target to generate assembly for a file
core/GameManager.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/core/GameManager.cpp.s
.PHONY : core/GameManager.cpp.s

err/Error.o: err/Error.cpp.o

.PHONY : err/Error.o

# target to build an object file
err/Error.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/err/Error.cpp.o
.PHONY : err/Error.cpp.o

err/Error.i: err/Error.cpp.i

.PHONY : err/Error.i

# target to preprocess a source file
err/Error.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/err/Error.cpp.i
.PHONY : err/Error.cpp.i

err/Error.s: err/Error.cpp.s

.PHONY : err/Error.s

# target to generate assembly for a file
err/Error.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/err/Error.cpp.s
.PHONY : err/Error.cpp.s

events/EventDispatcher.o: events/EventDispatcher.cpp.o

.PHONY : events/EventDispatcher.o

# target to build an object file
events/EventDispatcher.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/events/EventDispatcher.cpp.o
.PHONY : events/EventDispatcher.cpp.o

events/EventDispatcher.i: events/EventDispatcher.cpp.i

.PHONY : events/EventDispatcher.i

# target to preprocess a source file
events/EventDispatcher.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/events/EventDispatcher.cpp.i
.PHONY : events/EventDispatcher.cpp.i

events/EventDispatcher.s: events/EventDispatcher.cpp.s

.PHONY : events/EventDispatcher.s

# target to generate assembly for a file
events/EventDispatcher.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/events/EventDispatcher.cpp.s
.PHONY : events/EventDispatcher.cpp.s

events/InputHandler.o: events/InputHandler.cpp.o

.PHONY : events/InputHandler.o

# target to build an object file
events/InputHandler.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/events/InputHandler.cpp.o
.PHONY : events/InputHandler.cpp.o

events/InputHandler.i: events/InputHandler.cpp.i

.PHONY : events/InputHandler.i

# target to preprocess a source file
events/InputHandler.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/events/InputHandler.cpp.i
.PHONY : events/InputHandler.cpp.i

events/InputHandler.s: events/InputHandler.cpp.s

.PHONY : events/InputHandler.s

# target to generate assembly for a file
events/InputHandler.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/events/InputHandler.cpp.s
.PHONY : events/InputHandler.cpp.s

glfiles/Mesh.o: glfiles/Mesh.cpp.o

.PHONY : glfiles/Mesh.o

# target to build an object file
glfiles/Mesh.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/glfiles/Mesh.cpp.o
.PHONY : glfiles/Mesh.cpp.o

glfiles/Mesh.i: glfiles/Mesh.cpp.i

.PHONY : glfiles/Mesh.i

# target to preprocess a source file
glfiles/Mesh.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/glfiles/Mesh.cpp.i
.PHONY : glfiles/Mesh.cpp.i

glfiles/Mesh.s: glfiles/Mesh.cpp.s

.PHONY : glfiles/Mesh.s

# target to generate assembly for a file
glfiles/Mesh.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/glfiles/Mesh.cpp.s
.PHONY : glfiles/Mesh.cpp.s

glfiles/ObjLoader.o: glfiles/ObjLoader.cpp.o

.PHONY : glfiles/ObjLoader.o

# target to build an object file
glfiles/ObjLoader.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/glfiles/ObjLoader.cpp.o
.PHONY : glfiles/ObjLoader.cpp.o

glfiles/ObjLoader.i: glfiles/ObjLoader.cpp.i

.PHONY : glfiles/ObjLoader.i

# target to preprocess a source file
glfiles/ObjLoader.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/glfiles/ObjLoader.cpp.i
.PHONY : glfiles/ObjLoader.cpp.i

glfiles/ObjLoader.s: glfiles/ObjLoader.cpp.s

.PHONY : glfiles/ObjLoader.s

# target to generate assembly for a file
glfiles/ObjLoader.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/glfiles/ObjLoader.cpp.s
.PHONY : glfiles/ObjLoader.cpp.s

glfiles/Shader.o: glfiles/Shader.cpp.o

.PHONY : glfiles/Shader.o

# target to build an object file
glfiles/Shader.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/glfiles/Shader.cpp.o
.PHONY : glfiles/Shader.cpp.o

glfiles/Shader.i: glfiles/Shader.cpp.i

.PHONY : glfiles/Shader.i

# target to preprocess a source file
glfiles/Shader.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/glfiles/Shader.cpp.i
.PHONY : glfiles/Shader.cpp.i

glfiles/Shader.s: glfiles/Shader.cpp.s

.PHONY : glfiles/Shader.s

# target to generate assembly for a file
glfiles/Shader.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/glfiles/Shader.cpp.s
.PHONY : glfiles/Shader.cpp.s

glfiles/Textures.o: glfiles/Textures.cpp.o

.PHONY : glfiles/Textures.o

# target to build an object file
glfiles/Textures.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/glfiles/Textures.cpp.o
.PHONY : glfiles/Textures.cpp.o

glfiles/Textures.i: glfiles/Textures.cpp.i

.PHONY : glfiles/Textures.i

# target to preprocess a source file
glfiles/Textures.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/glfiles/Textures.cpp.i
.PHONY : glfiles/Textures.cpp.i

glfiles/Textures.s: glfiles/Textures.cpp.s

.PHONY : glfiles/Textures.s

# target to generate assembly for a file
glfiles/Textures.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/glfiles/Textures.cpp.s
.PHONY : glfiles/Textures.cpp.s

lib/stb_image.o: lib/stb_image.c.o

.PHONY : lib/stb_image.o

# target to build an object file
lib/stb_image.c.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/lib/stb_image.c.o
.PHONY : lib/stb_image.c.o

lib/stb_image.i: lib/stb_image.c.i

.PHONY : lib/stb_image.i

# target to preprocess a source file
lib/stb_image.c.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/lib/stb_image.c.i
.PHONY : lib/stb_image.c.i

lib/stb_image.s: lib/stb_image.c.s

.PHONY : lib/stb_image.s

# target to generate assembly for a file
lib/stb_image.c.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/lib/stb_image.c.s
.PHONY : lib/stb_image.c.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/main.cpp.s
.PHONY : main.cpp.s

sdlfiles/Display.o: sdlfiles/Display.cpp.o

.PHONY : sdlfiles/Display.o

# target to build an object file
sdlfiles/Display.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/sdlfiles/Display.cpp.o
.PHONY : sdlfiles/Display.cpp.o

sdlfiles/Display.i: sdlfiles/Display.cpp.i

.PHONY : sdlfiles/Display.i

# target to preprocess a source file
sdlfiles/Display.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/sdlfiles/Display.cpp.i
.PHONY : sdlfiles/Display.cpp.i

sdlfiles/Display.s: sdlfiles/Display.cpp.s

.PHONY : sdlfiles/Display.s

# target to generate assembly for a file
sdlfiles/Display.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/sdlfiles/Display.cpp.s
.PHONY : sdlfiles/Display.cpp.s

utils/Settings.o: utils/Settings.cpp.o

.PHONY : utils/Settings.o

# target to build an object file
utils/Settings.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/utils/Settings.cpp.o
.PHONY : utils/Settings.cpp.o

utils/Settings.i: utils/Settings.cpp.i

.PHONY : utils/Settings.i

# target to preprocess a source file
utils/Settings.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/utils/Settings.cpp.i
.PHONY : utils/Settings.cpp.i

utils/Settings.s: utils/Settings.cpp.s

.PHONY : utils/Settings.s

# target to generate assembly for a file
utils/Settings.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/utils/Settings.cpp.s
.PHONY : utils/Settings.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... engine"
	@echo "... edit_cache"
	@echo "... Camera.o"
	@echo "... Camera.i"
	@echo "... Camera.s"
	@echo "... GameLoop.o"
	@echo "... GameLoop.i"
	@echo "... GameLoop.s"
	@echo "... Transform.o"
	@echo "... Transform.i"
	@echo "... Transform.s"
	@echo "... core/GameManager.o"
	@echo "... core/GameManager.i"
	@echo "... core/GameManager.s"
	@echo "... err/Error.o"
	@echo "... err/Error.i"
	@echo "... err/Error.s"
	@echo "... events/EventDispatcher.o"
	@echo "... events/EventDispatcher.i"
	@echo "... events/EventDispatcher.s"
	@echo "... events/InputHandler.o"
	@echo "... events/InputHandler.i"
	@echo "... events/InputHandler.s"
	@echo "... glfiles/Mesh.o"
	@echo "... glfiles/Mesh.i"
	@echo "... glfiles/Mesh.s"
	@echo "... glfiles/ObjLoader.o"
	@echo "... glfiles/ObjLoader.i"
	@echo "... glfiles/ObjLoader.s"
	@echo "... glfiles/Shader.o"
	@echo "... glfiles/Shader.i"
	@echo "... glfiles/Shader.s"
	@echo "... glfiles/Textures.o"
	@echo "... glfiles/Textures.i"
	@echo "... glfiles/Textures.s"
	@echo "... lib/stb_image.o"
	@echo "... lib/stb_image.i"
	@echo "... lib/stb_image.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... sdlfiles/Display.o"
	@echo "... sdlfiles/Display.i"
	@echo "... sdlfiles/Display.s"
	@echo "... utils/Settings.o"
	@echo "... utils/Settings.i"
	@echo "... utils/Settings.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

